### ISSUE TITLE
[BUG]: CI scripts do not enable errexit

### ISSUE THREAD

**Issue by theoreticalbts** [koinos/koinos-proto#172]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Currently the CI scripts do not propagate errors to the caller.

I believe there's a typo in `install.sh`, specifically [here](https://github.com/koinos/koinos-proto/blob/0050f4b032a8e728e1ce81bc275e2948f8f2f054/ci/install.sh#L27):  `nvm usm $NODE_VERSION` should be `nvm use`

This is maybe causing some silent malfunction in the CI pipeline.

### Expected behavior

Shell scripts should use `set -e` to enable `errexit` mode ("Exit immediately if a command exits with a non-zero status" according to Bash's `help set`).

### Environment

```markdown
- OS: Travis
```

### Anything else?

I've made a bit of progress toward replacing CI scripts with a Dockerfile.  If the above-mentioned typo isn't the only error being masked by the `set -e` issue, and more extensive analysis / refactoring of CI scripts is deemed necessary, perhaps some work can be saved by integrating my PR (see #171).

**Comment by mvandeberg** [comment]
After enabling errexit, some after success actions are not working correctly.
