### ISSUE TITLE
[FEATURE]: Update version of generated repositories when tagging

### ISSUE THREAD

**Issue by sgerbino** [koinos/koinos-proto#225]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New feature

In `koinos-proto-cpp` for example, we should update the `VERSION` in the `project()` call programmatically.

**Comment by mvandeberg** [comment]
The PR did not work. Reopening for next release.

**Comment by sgerbino** [comment]
Resolved by #246.

**Comment by mvandeberg** [comment]
Worked! https://github.com/koinos/koinos-proto-cpp/commit/be14c4fcf429b2b69b17a983e5922f5ce4910a65
