### ISSUE TITLE
[FEATURE]: jsonrpc method to query p2p for current claimed block height by peers

### ISSUE THREAD

**Issue by sneak** [koinos/koinos-proto#81]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New feature

I've a syncing testnet node that is at block 112k and counting.  Obviously the chain service can't vouch for a block height that it hasn't processed/validated/committed, but the p2p service knows that more blocks hypothetically exist (because it's fetching them as it syncs).

It would be nice to have an rpc that lets me query the p2p service for what it thinks the approximate total number of blocks in chain are (based on claims from peers) so that I can estimate percentage of the chain that is synced.  `bitcoind` for example outputs a percentage with each block application.  It would also be nice if the chain microservice could publish a similar percentage in its "Block application successful" log message.

### Anything else?

The output from `chain.get_head_info` includes a `last_irreversible_block` but that's just locally, not of the whole network.

**Comment by mvandeberg** [comment]
The chain microservice should not rely on p2p. But chain does now outputs estimates of how much blockchain time is left to sync (based on system time and the time of the head block).
